{"La Nacion": {
    "Titulos ed. impresa": "http://contenidos.lanacion.com.ar/herramientas/rss/origen=1",
    "Politica": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=30",
    "Economia": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=272",
    "Deportes": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=131",
    "Sociedad": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7773",
    "Seguridad": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7775",
    "Buenos Aires": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7774",
    "Opinion": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=28",
    "Espectaculos": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=120",
    "El Mundo": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7",
    "Revista LA NACION": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=494",
    "Suplemento Enfoques": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=421",
    "Suplemento Comercio Exterior": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=347",
    "Suplemento Tecnologia": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=432",
    "Suplemento Turismo": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=504",
    "Suplemento Al volante": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=371",
    "Suplemento El Campo": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=337",
    "Suplemento Moda y Belleza": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1312",
    "Suplemento Inmuebles Comerciales": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1363",
    "Suplemento Countries": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1348",
    "Suplemento Comunidad": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1344",
    "adnCultura": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=6734",
    "The Wall Street Journal Americas": "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=6373"
}
}
